### PR TITLE
Remove componentWillMount

### PR DESCRIPTION
**Pull request by nguyenductoan1995**

### CODE REVIEW

**Comment by poberwong** [comment]
Good job. I will review it at night.

**Comment by nguyenductoan1995** [comment]
Thank you, Good night !

Vào 11:06, CN, 15 thg 9, 2019 PoberWong <notifications@github.com> đã viết:

**Comment by poberwong** [comment]
I'm sorry that the pull-request will be closed due to incorrect performance. It's absolutely right to remove `componentWillReceiveProps` and use `getDerivedStateFromProps` instead, but it could be better to run the example project in the library to test whether the pull-request is right.

The video recorded:

1. wrong behavior
2. state changed without animation.

**Comment by poberwong** [comment]
If you run it perfectly, please launch a new pull-request and I will publish 2.0.0 by it.

**Pull request closed without merging**
